-- MySQL Script generated by MySQL Workbench
-- Sun Nov 28 16:56:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`carrinho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`carrinho` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`carrinho` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `id_cliente` BIGINT(20) NULL DEFAULT NULL,
  `id_produto` BIGINT(20) NULL DEFAULT NULL,
  `qtdeProduto` VARCHAR(10) NULL DEFAULT NULL,
  `status` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CarrinhoCliente` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_CarrinhoProduto` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_CarrinhoCliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `ecommerce`.`cliente` (`id`),
  CONSTRAINT `fk_CarrinhoProduto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `ecommerce`.`produto` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`cartaocredito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`cartaocredito` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`cartaocredito` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nCartao` VARCHAR(20) NULL DEFAULT NULL,
  `bandeira` VARCHAR(15) NULL DEFAULT NULL,
  `nome` VARCHAR(30) NULL DEFAULT NULL,
  `validade` VARCHAR(10) NULL DEFAULT NULL,
  `cvv` VARCHAR(5) NULL DEFAULT NULL,
  `preferencial` VARCHAR(10) NULL DEFAULT NULL,
  `id_cliente` BIGINT(20) NULL DEFAULT NULL,
  `dt_cadastro` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CartaoCliente` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_CartaoCliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `ecommerce`.`cliente` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`cliente` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`cliente` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL DEFAULT NULL,
  `cpf` VARCHAR(14) NULL DEFAULT NULL,
  `dt_nasc` DATE NULL DEFAULT NULL,
  `genero` VARCHAR(10) NULL DEFAULT NULL,
  `telefone` VARCHAR(12) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `senha` VARCHAR(20) NULL DEFAULT NULL,
  `status` VARCHAR(10) NULL DEFAULT NULL,
  `tipo` VARCHAR(10) NULL DEFAULT NULL,
  `dt_cadastro` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`cupom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`cupom` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`cupom` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL DEFAULT NULL,
  `tipo` VARCHAR(20) NULL DEFAULT NULL,
  `valor` VARCHAR(10) NULL DEFAULT NULL,
  `id_cliente` BIGINT(20) NULL DEFAULT NULL,
  `utilizado` VARCHAR(3) NULL DEFAULT NULL,
  `dt_cadastro` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ClienteCupom` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_ClienteCupom`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `ecommerce`.`cliente` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`cuponsnocarrinho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`cuponsnocarrinho` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`cuponsnocarrinho` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `id_cupom` BIGINT(20) NULL DEFAULT NULL,
  `id_cliente` BIGINT(20) NULL DEFAULT NULL,
  `valor` VARCHAR(10) NULL DEFAULT NULL,
  `status` VARCHAR(10) NULL DEFAULT NULL,
  `dt_cadastro` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cupom` (`id_cupom` ASC) VISIBLE,
  CONSTRAINT `fk_Cupom`
    FOREIGN KEY (`id_cupom`)
    REFERENCES `ecommerce`.`cupom` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`endereco` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`endereco` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(10) NULL DEFAULT NULL,
  `logradouro` VARCHAR(50) NULL DEFAULT NULL,
  `numero` VARCHAR(10) NULL DEFAULT NULL,
  `bairro` VARCHAR(30) NULL DEFAULT NULL,
  `cidade` VARCHAR(50) NULL DEFAULT NULL,
  `estado` VARCHAR(10) NULL DEFAULT NULL,
  `pais` VARCHAR(20) NULL DEFAULT NULL,
  `tipoResidencia` VARCHAR(20) NULL DEFAULT NULL,
  `observacoes` VARCHAR(20) NULL DEFAULT NULL,
  `tipoEndereco` VARCHAR(20) NULL DEFAULT NULL,
  `id_cliente` BIGINT(20) NULL DEFAULT NULL,
  `dt_cadastro` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_EnderecoCliente` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_EnderecoCliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `ecommerce`.`cliente` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`estoque` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`estoque` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `id_produto` BIGINT(20) NULL DEFAULT NULL,
  `tipo` VARCHAR(10) NULL DEFAULT NULL,
  `quantidade` VARCHAR(10) NULL DEFAULT NULL,
  `valorCompra` VARCHAR(10) NULL DEFAULT NULL,
  `dt_entrada` DATE NULL DEFAULT NULL,
  `quantidadeTotal` VARCHAR(10) NULL DEFAULT NULL,
  `dt_cadastro` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_EstoqueProduto` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_EstoqueProduto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `ecommerce`.`produto` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`item_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`item_pedido` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`item_pedido` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `id_produto` BIGINT(20) NULL DEFAULT NULL,
  `nome` VARCHAR(40) NULL DEFAULT NULL,
  `qtdeProduto` VARCHAR(10) NULL DEFAULT NULL,
  `precoVenda` VARCHAR(10) NULL DEFAULT NULL,
  `id_pedido` BIGINT(20) NULL DEFAULT NULL,
  `dt_pedido` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ProdutoItem` (`id_produto` ASC) VISIBLE,
  INDEX `fk_PedidoItem` (`id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_PedidoItem`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `ecommerce`.`pedido` (`id`),
  CONSTRAINT `fk_ProdutoItem`
    FOREIGN KEY (`id_produto`)
    REFERENCES `ecommerce`.`produto` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`pedido` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`pedido` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `precoTotalProduto` VARCHAR(10) NULL DEFAULT NULL,
  `precoFrete` VARCHAR(10) NULL DEFAULT NULL,
  `precoTotal` VARCHAR(10) NULL DEFAULT NULL,
  `statusPedido` VARCHAR(30) NULL DEFAULT NULL,
  `id_cliente` BIGINT(20) NULL DEFAULT NULL,
  `id_endereco` BIGINT(20) NULL DEFAULT NULL,
  `cartao1` BIGINT(20) NULL DEFAULT NULL,
  `valorCartao1` VARCHAR(10) NULL DEFAULT NULL,
  `cartao2` BIGINT(20) NULL DEFAULT NULL,
  `valorCartao2` VARCHAR(10) NULL DEFAULT NULL,
  `desconto` VARCHAR(10) NULL DEFAULT NULL,
  `dt_pedido` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ClientePedido` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_EnderecoPedido` (`id_endereco` ASC) VISIBLE,
  INDEX `fk_CartaoPedido1` (`cartao1` ASC) VISIBLE,
  INDEX `fk_CartaoPedido2` (`cartao2` ASC) VISIBLE,
  CONSTRAINT `fk_CartaoPedido1`
    FOREIGN KEY (`cartao1`)
    REFERENCES `ecommerce`.`cartaocredito` (`id`),
  CONSTRAINT `fk_CartaoPedido2`
    FOREIGN KEY (`cartao2`)
    REFERENCES `ecommerce`.`cartaocredito` (`id`),
  CONSTRAINT `fk_ClientePedido`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `ecommerce`.`cliente` (`id`),
  CONSTRAINT `fk_EnderecoPedido`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `ecommerce`.`endereco` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce`.`produto` ;

CREATE TABLE IF NOT EXISTS `ecommerce`.`produto` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(40) NULL DEFAULT NULL,
  `descricao` VARCHAR(300) NULL DEFAULT NULL,
  `categoria` VARCHAR(20) NULL DEFAULT NULL,
  `cores` VARCHAR(50) NULL DEFAULT NULL,
  `tamanho` VARCHAR(20) NULL DEFAULT NULL,
  `precoCompra` VARCHAR(10) NULL DEFAULT NULL,
  `precoVenda` VARCHAR(10) NULL DEFAULT NULL,
  `qtdeEstoque` VARCHAR(10) NULL DEFAULT NULL,
  `foto` VARCHAR(50) NULL DEFAULT NULL,
  `dt_cadastro` DATE NULL DEFAULT NULL,
  `status` VARCHAR(10) NULL DEFAULT NULL,
  `grupoPrecificacao` VARCHAR(30) NULL DEFAULT NULL,
  `descricaoStatusProduto` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
